server:
  port: 8081

spring:
  profiles:
    include: migration

  jpa:
    legacy-ad:
      hikari:
        maximum-pool-size: 100
    recent-ad:
      hikari:
        maximum-pool-size: 100

  cloud:
    stream:
      binders:
        legacy-rabbit1:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5673
              username: user
              password: user
              virtual-host: legacy
      bindings:
        legacyConsumer-in-0:
          binder: legacy-rabbit1
          destination: legacy-topic
          group: migration
logging:
  file:
    name: logs/gradual.log
