spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3309/dsp_legacy
        username: root
        password: user
        maximum-pool-size: 100
      properties:
        hibernate:
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy