spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3309/dsp_legacy
        username: root
        password: user
        maximum-pool-size: 100
      properties:
        hibernate:
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  cloud:
    stream:
      binders:
        legacy-rabbit1:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5673
              username: user
              password: user
              virtual-host: legacy
      bindings:
        legacy-rabbit-out:
          binder: legacy-rabbit1
          destination: legacy-topic

