spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3309/dsp_legacy
        username: root
        password: user
        maximum-pool-size: 100
      properties:
        hibernate:
          ddl-auto: update
          show-sql: true
          physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy