services:
  dsp-migration-mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=dsp_legacy
      - MYSQL_ROOT_PASSWORD=user
      - TZ=UTC
    volumes:
      - ./data/legacy-db:/var/lib/mysql

  dsp-migration-postgresql:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=user
    volumes:
      - ./data/recent-db:/var/lib/postgresql/data