services:
  dsp-migration-mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=dsp_legacy
      - MYSQL_ROOT_PASSWORD=user
      - TZ=UTC
    volumes:
      - ./data/legacy-db:/var/lib/mysql

  dsp-migration-postgresql:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=user
    volumes:
      - ./data/recent-db:/var/lib/postgresql/data

  dsp-rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
      RABBITMQ_DEFAULT_VHOST: legacy

  dsp-kafka:
    image: bitnami/kafka:3.6.2
    ports:
      - "9194:9194"
    restart: always
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9193,EXTERNAL://:9194
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://dsp-kafka:9192,EXTERNAL://localhost:9194
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9193
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  dsp-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: dsp-kafka-ui
    ports:
      - "7081:8080"
    restart: always
    depends_on:
      - dsp-kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: dsp-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: dsp-kafka:9192
