###
POST http://localhost:8080/campaign/v1
Content-Type: application/json

{
  "name": "캠페인",
  "userId": 6,
  "budget": 10000
}

###
GET http://localhost:8080/campaign/v1/1

###
PATCH http://localhost:8080/campaign/v1/name
Content-Type: application/json

{
  "id": 2,
  "name": "campaign__new"
}

###
PATCH http://localhost:8080/campaign/v1/budget
Content-Type: application/json

{
  "id": 2,
  "budget": 2000
}

###
DELETE http://localhost:8080/campaign/v1/1