###
POST http://localhost:8080/keyword/v1
Content-Type: application/json

{
  "text": "키워드333",
  "adGroupId": 2
}

###
GET http://localhost:8080/keyword/v1/1

###
DELETE http://localhost:8080/keyword/v1/4